/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.jbudget125914;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Test");
    }
}
